name: npm-publish
on:
  push:
    branches:
      - mongo/0.1
jobs:
  npm-publish:
    name: npm-publish-mongo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
    - run: npm ci --workspace @kelchy/mongo --include-dev
    - run: npm run --workspace @kelchy/mongo test:unit
    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.8
      with:
        tag_name: "mongo/v%s"
        tag_message: "mongo/v%s"
        create_tag: "true"
        commit_pattern: "^Release (\\S+)"
        workspace: "./lib/mongo"
        publish_command: "npm"
        publish_args: "--workspace @kelchy/mongo"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
